#!/bin/bash

echo "Job Agent - Supabase Setup Helper"
echo "================================="
echo ""
echo "This script helps you configure Supabase for the Job Agent."
echo ""
echo "1. Create a new project at https://supabase.com/dashboard"
echo "2. Go to Project Settings > API and copy the URL and Anon Key."
echo "3. Update .env with these values."
echo ""
echo "4. Go to SQL Editor in Supabase Dashboard and run the following SQL to enable Storage:"
echo ""
echo "-- Enable Storage"
echo "insert into storage.buckets (id, name, public) values ('resumes', 'resumes', false);"
echo "create policy \"Authenticated users can upload resumes\" on storage.objects for insert with check (bucket_id = 'resumes' and auth.uid() = owner);"
echo "create policy \"Users can view their own resumes\" on storage.objects for select using (bucket_id = 'resumes' and auth.uid() = owner);"
echo ""
echo "5. To apply the database schema, you can use Prisma if you have the connection string:"
echo "   npx prisma db push"
echo ""
echo "   Or copy the SQL from prisma/schema.prisma (requires converting Prisma schema to SQL, which 'prisma migrate' does)."
echo ""
echo "Setup complete!"
